#!/usr/bin/env python3
import subprocess
from email.utils import parseaddr
from urllib.parse import quote
import common

args, ignored = common.parse_args()
reviewerEmail, reviewerName = parseaddr(args.reviewer)
auth_token, section_config = common.parse_config(__file__)

if common.is_email_matching(section_config.get('verificator_emails'), reviewerEmail):
    proc = subprocess.Popen(['ssh', url, '-p', '29418', 'gerrit', 'query',
                             args.changeId, '--submit-records', '--current-patch-set', '--format', 'JSON'])
    outs, errs = proc.communicate()

if args.isDraft == 'true' or args.codeReviewScore is None:
    exit()

changeOwnerEmail, changeOwnerName = parseaddr(args.changeOwner)

colors = {'-2': 'red', '-1': 'yellow', '1': 'purple', '2': 'green'}
color = colors.get(args.codeReviewScore, 'gray')

ownerMentionName = '@' + changeOwnerEmail.split('@')[0].replace('.', '')
room = args.project + ' alerts'
url = 'https://api.hipchat.com/v2/room/%s/notification?auth_token=%s' % (quote(room), quote(auth_token))
message = '%s, change %s reviewed, score: %s' % (ownerMentionName, args.changeUrl, args.codeReviewScore)
success_log_message = 'Comment message added to %s' % room

common.perform_request(url, message, success_log_message, color)
